debug: false
logging:
  level:
    com.example.wondugallery: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: ENC(NYzbxy2qlObzPzG8x7q2b/Q1jFDTWm2kPfQ9LdXXG1+Q6colYViDnJH8OJRduz6n)
    username: ENC(c2TmUBeNVvJkmV2hplAhgw==)
    password: ENC(Y4xssGyNP75CKqMK4WUQZjHq91G/5S42)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100




