debug: false
logging:
  level:
    com.example.wondugallery: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: ENC(pa4uqnXuFANSC7+aOVWjbMQfYd0pwQKUwQtvVpb/N1XQWZhFlLlRBbY4uPtbwavb)
    username: ENC(RraqcVraoTgYuyfrdxxX8w==)
    password: ENC(JcSBW5QGXfEFA77ONB8Fk+0ZuroehWST)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100




