debug: false
logging:
  level:
    com.example.wondugallery: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:mysql://141.164.53.210:3306/TEST
    username: ENC(RraqcVraoTgYuyfrdxxX8w==)
    password: ENC(lQy4Qwz/q6+gyOiDYT9KDg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100




