debug: false
logging:
  level:
    com.example.wondugallery: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: ENC(tVuJ4eXj4OTNd7ze0lUVsBu/J9oSnTCG2vIOLTNTSagW3CywgEuNcTm3ji3Xr9/x)
    username: ENC(6fSDGDDBaScd8kZiLg9Tykt8KGmqp2Su)
    password: ENC(9kfy/aAIe+bwZPCvRdSJkKY4zSxc2MbR)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100




