server:
  port: 8100
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
    max-http-form-post-size: 20MB

spring:
  datasource:
    url: ENC(pjLznbyFCmeA2jvUfx1pD1UGtSVxFi18YaU7hHxfDoyyhjIcwyjZCBiHT30auXDO)
    username: ENC(uOJ2Dzx1JOlZ22zvIYT22Q==)
    password: ENC(Vho5daxlktHSKJD/nMzHvw+X3kWNAGRh)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      location: D:/files
cloud:
  aws:
    credentials:
      access-key: ENC(A+xe62iDcXcr4ePsBySdY7ep+Poi/xdc43Q+P9WWC8Q=)
      secret-key: ENC(w4OVdRM/fN1vV5sZDOMWBd4Oxk7ZgsymdzgMgoxTPMgrc39C5rSUj6ub9FtfAw+tlrnGSvjenqU=)
    s3:
      bucket: wondus3
      storage: STANDARD
    region:
      static: ap-northeast-2
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt.password}
    algorithm: ${jasypt.algorithm}



