server:
  port: 8100
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
    max-http-form-post-size: 20MB

spring:
  datasource:
    url: ENC(a4Ac9Qgbw359oWNCjiddtEPQ94U6fy8P8NwAJ2WdCsJ0h/gt9U5XbS8fHU3UdXru)
    username: ENC(7QrHHpROCEp/ZzO++b/v7Q==)
    password: ENC(vLMcI/79GniFtcAmuUehrbLAPTLApdnU)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: D:/Temp
      max-file-size: 200MB
      max-request-size: 200MB
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
cloud:
  aws:
    credentials:
      access-key: ENC(TNEz6+LpttbYPW4Rg97lhGhkGascAWR84XxSaAD4XgM=)
      secret-key: ENC(olC60+Z+I+osV+B8K7oF1VJnj5mb6S91g4vLWFcyCOWfWufMoQ7cybpI9m1u42gXip1gcEWZi44=)
    s3:
      bucket: wondu-file-storge
      storage: STANDARD
    region:
      static: ap-northeast-2
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt.password}
    algorithm: ${jasypt.algorithm}



